#!/bin/bash

FILE="$HOME/.cache/eww_launch.keybinds"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many bindkeys hyprland archlx
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close bindkeys hyprland archlx
	rm "$FILE"
fi
