# Colors
include rouge2.conf
# include rose-pine.conf

# Fonts
# font_family									Comic Code Ligatures
font_family                   Cascadia Code
font_size        							11
font_features     CascadiaCode-SemiBoldItalic     calt zero +ss01
font_features     CascadiaCode-LightItalic        calt zero +ss01
font_features     CascadiaCode-ExtraLightItalic   calt zero +ss01
font_features     CascadiaCode-Italic             calt zero +ss01
font_features     CascadiaCode-BoldItalic         calt zero +ss01
font_features     CascadiaCode-SemiLightItalic    calt zero +ss01

# Cursor
cursor_shape     							underline
cursor_underline_thickness    2.0

allow_remote_control yes
listen_on unix:@mykitty

# Window
remember_window_size   				no
initial_window_width   				1000
initial_window_height  				500
window_border_width 					0
window_margin_width 					0.4 4
window_padding_width 					3
background_opacity 						0.8

# Tabs
tab_bar_edge 								  bottom
tab_bar_style 							  powerline
active_tab_font_style 				bold
inactive_tab_font_style 			normal

map ctrl+shift+right          next_window
map ctrl+shift+left           previous_window
