lastupdatecheck: 0
recentrepos:
    - /home/frvnzj/.dotfiles
    - /home/frvnzj/Gits/xnvimx
    - /home/frvnzj/Documentos/principhialab/webpage/principhiaweb
    - /home/frvnzj/Documentos/Blog/xJAVIERx
startuppopupversion: 5
lastversion: 0.43.1
customcommandshistory:
    - close
    - q!
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
renamesimilaritythreshold: 50
localbranchsortorder: recency
remotebranchsortorder: alphabetical
gitlogorder: topo-order
gitlogshowgraph: always
