#!/bin/bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Catppuccin-Mocha-Standard-Sapphire-Dark'
ICONS='Papirus-Dark'
CURSOR='Catppuccin-Mocha-Dark'
FONT='SF Pro 10'
SCHEME='prefer-dark'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
	${SCHEMA} color-scheme "$SCHEME"
}

apply_themes
