#!/bin/bash

cache_file="$HOME/.cache/wallpaper_actual"
rasi_file="$HOME/.cache/current_wallpaper.rasi"

if [ ! -f $cache_file ]; then
    touch $cache_file
    echo "$HOME/Pictures/walswww/wallpaper.jpg" > "$cache_file"
fi

if [ ! -f $rasi_file ] ;then
    touch $rasi_file
    echo "* { current-image: url(\"$HOME/Pictures/walswww/wallpaper.jpg\", height); }" > "$rasi_file"
fi

wallpaper_actual=$(cat "$cache_file")

case $1 in

    "init")
        if [ -f $cache_file ]; then
            wal -q -i $wallpaper_actual
        else
            wal -q -i ~/Pictures/walswww/
        fi
    ;;

    "select")
        elegir=$(find "$HOME/Pictures/walswww" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec basename {} \; | sort -R | while read rfile
        do
            echo -en "$rfile\x00icon\x1f$HOME/Pictures/walswww/${rfile}\n"
        done | rofi -dmenu -replace -config ~/.config/rofi/config-wallpaper.rasi)
        if [ ! "$elegir" ]; then
            echo "No se seleccionó wallpaper"
            exit
        fi
        wal -q -i ~/Pictures/walswww/$elegir
    ;;

    *)
        wal -q -i ~/Pictures/walswww/
    ;;

esac

source "$HOME/.cache/wal/colors.sh"
echo "Wallpaper: $wallpaper"

echo "$wallpaper" > "$cache_file"
echo "* { current-image: url(\"$wallpaper\", height); }" > "$rasi_file"

~/.config/waybar/launch

transition_type="random"

swww img $wallpaper \
    --transition-bezier .43,1.19,1,.4 \
    --transition-fps=60 \
    --transition-type=$transition_type \
    --transition-duration=0.7 \
    --transition-pos "$( hyprctl cursorpos )"

sleep 1

echo "DONE!"
