#!/bin/sh

export BEMENU_OPTS='-H 24 -l 10 --fb "#1e1e2e" --ff "#94e2d5" --nb "#1e1e2e" --nf "#f5e0dc" --tb "#1e1e2e" --hb "#1e1e2e" --tf "#cba6f7" --hf "#89b4fa" --nf "#f5e0dc" --af "#f5e0dc" --ab "#1e1e2e" --fn "SF Pro 10"'

man -k . | bemenu -p '📑 MANPDF' | awk '{print $1}' | xargs -r man -Tpdf | zathura -
