#!/bin/dash

file=$(fd -tf | bemenu -i -l 10 -H 24 --fb "#1e1e2e" --ff "#94e2d5" --nb "#1e1e2e" --nf "#f5e0dc" --tb "#1e1e2e" --hb "#1e1e2e" --tf "#cba6f7" --hf "#89b4fa" --nf "#f5e0dc" --af "#f5e0dc" --ab "#1e1e2e" -p ' Enviar 🔗:')


if [ "$file" ]; then

  curl -F "file=@$file" https://0x0.st | wl-copy
  notify-send "Link en clipboard 📎"

else
  
  exit 1

fi
