#!/usr/bin/bash
swaylock \
--screenshots \
--indicator \
--clock \
--inside-wrong-color 1f1d2e  \
--ring-wrong-color 161925  \
--inside-clear-color 1f1d2e \
--ring-clear-color 161925 \
--inside-ver-color 89b4fa \
--ring-ver-color 161925 \
--text-color e0def4 \
--indicator-radius 200 \
--indicator-thickness 20 \
--effect-blur 5x5 \
--effect-vignette 0.4:0.4 \
--ring-color 161925 \
--key-hl-color f5c2e7 \
--line-color 313244 \
--inside-color 00161925 \
--separator-color 00000000 \
--fade-in 0.2 &

# sleep 2; ~/.config/hypr/scripts/screenshot_full
