#!/bin/dash

export BEMENU_OPTS='-i -l 20 -H 20 --fb "#1e1e2e" --ff "#94e2d5" --nb "#1e1e2e" --nf "#f5e0dc" --tb "#1e1e2e" --hb "#1e1e2e" --tf "#cba6f7" --hf "#89b4fa" --nf "#f5e0dc" --af "#f5e0dc" --ab "#1e1e2e" --fn "Liga SFMono Nerd Font 10"'

bat ~/.scripts/nerdfont.txt | bemenu -p " NerdIcon 📋:" | awk '{print $1}' | wl-copy -n

notify-send "NerdIcon en clipboard 📎"
