#!/bin/sh

cd $HOME/Documentos/Refs-PDF/
pdf=$(ls | bat | dmenu -x 9 -y 10 -z 1350 -i -l 10 -nb "#1e222a" -nf "#abb2bf" -sb "#5c6370" -sf "#abb2bf" -fn "JetBrainsMono Nerd Font:size=10" -p 'Leer:')
zathura "$pdf"
