require "xJAVIERx.launch"
require "xJAVIERx.options"
require "xJAVIERx.keymaps"
require "xJAVIERx.autocmds"
spec "xJAVIERx.colorscheme"
spec "xJAVIERx.devicons"
spec "xJAVIERx.treesitter"
-- spec "xJAVIERx.lsp-zero"
spec "xJAVIERx.mason"
spec "xJAVIERx.schemastore"
spec "xJAVIERx.lspconfig"
spec "xJAVIERx.cmp"
spec "xJAVIERx.telescope"
spec "xJAVIERx.bibtelescope"
spec "xJAVIERx.gitsigns"
spec "xJAVIERx.none-ls"
spec "xJAVIERx.whichkey"
spec "xJAVIERx.neotree"
-- spec "xJAVIERx.nvimtree"
spec "xJAVIERx.comment"
-- spec "xJAVIERx.feline"
spec "xJAVIERx.lualine"
spec "xJAVIERx.bufferline"
-- spec "xJAVIERx.navic"
-- spec "xJAVIERx.breadcrumbs"
spec "xJAVIERx.ultimate-autopair"
-- spec "xJAVIERx.neogit"
spec "xJAVIERx.fugitive"
spec "xJAVIERx.diffview"
spec "xJAVIERx.alpha"
spec "xJAVIERx.netrw"
spec "xJAVIERx.neorg"
spec "xJAVIERx.project"
spec "xJAVIERx.toggleterm"
spec "xJAVIERx.neoscroll"
spec "xJAVIERx.surround"
spec "xJAVIERx.todo-comments"
-- spec "xJAVIERx.ufo"
spec "xJAVIERx.colorizer"
spec "xJAVIERx.dressing"
-- spec "xJAVIERx.noice"
spec "xJAVIERx.bufdelete"
spec "xJAVIERx.pasteimage"
spec "xJAVIERx.typst"
spec "xJAVIERx.peek"
spec "xJAVIERx.markmap"
spec "xJAVIERx.fidget"
spec "xJAVIERx.vim-socrates"
spec "xJAVIERx.undotree"
require "xJAVIERx.lazy"
